[window]
padding.x = 2
padding.y = 2

[font]
size = 10.0

[colors.primary]
background = '#FFFFFF'
foreground = '#434343'

[colors.cursor]
text = '#FFFFFF'
cursor = '#434343'

[colors.normal]
black = '#000000'
red = '#AA3731'
green = '#448C27'
yellow = '#CB9000'
blue = '#325CC0'
magenta = '#7A3E9D'
cyan = '#0083B2'
white = '#BBBBBB'

[colors.bright]
black = '#777777'
red = '#F05050'
green = '#60CB00'
yellow = '#FFBC5D'
blue = '#007ACC'
magenta = '#E64CE6'
cyan = '#00AACB'
white = '#FFFFFF'

[cursor]
style.shape = "Beam"
style.blinking = "Always"
blink_interval = 500
blink_timeout = 0
